name: ecfg

up:
  - homebrew:
      - dpkg
  - ruby: 2.1.6
  - go: '1.7'
  - bundler

commands:
  build: make
  run-built: build/bin/darwin-amd64
  test: go test ./...

packages:
  - git@github.com:Shopify/dev-shopify.git

