.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ECFG\-ENCRYPT" "1" "July 2016" "Shopify" "Version 0.2.0"
.
.SH "NAME"
\fBecfg\-encrypt\fR \- encrypt an ecfg file
.
.SH "SYNOPSIS"
\fBecfg encrypt\fR [\fB\-t\fR|\fB\-\-type\fR \fIfiletype\fR] [\fIfile\fR]
.
.SH "DESCRIPTION"
\fBefcg encrypt\fR encrypts any unencrypted data in the given file or, if no filename is given, \fBstdin\fR\.
.
.P
If a filename is given, that file will be modified in place; or, if the data is being read from \fBstdin\fR, the encrypted file will be written to \fBstdout\fR\.
.
.P
See ecfg(5) for information on the structure of an encryptable file\.
.
.SH "OPTIONS"
.
.TP
\fB\-t\fR, \fB\-\-type\fR="json|yaml|toml"
Specify the filetype\. Required when passing data from \fBstdin\fR and when \fIfile\fR does not end in "\.ecfg\.json", "\.ecfg\.yaml", or "\.ecfg\.toml"\.
.
.SH "SEE ALSO"
ecfg(1), ecfg\-decrypt(1), ecfg\-keygen(1), ecfg(5)
